### ISSUE TITLE
`SharedSliceVariation` doesn't have `slice_type`

### ISSUE THREAD

**Issue by Klynger** [prismicio/prismic-types#44]
### Versions

- @prismicio/types: @0.1.29
- node: 16.14.2

### Reproduction

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/8517023/175977194-3c7efdf1-2174-4d8b-bd97-cc57bea50714.png">

### Steps to reproduce

Just use the type

### What is expected?

The type to have a definition for `slice_type`.

### What is actually happening?

The type doesn't have a definition for `slice_type`

**Comment by angeloashmore** [comment]
Hi @Klynger,

Thanks for reporting this issue. This is actually intentional; `SharedSliceVariation` is intended to be used along with `SharedSlice`. `SharedSlice` contains `slice_type` and accepts a union of `SharedSliceVariation` types.

You can see the `SharedSlice` type definition here: https://github.com/prismicio/prismic-types/blob/f7c39e38ead6aae8527dd07259359f6fab610c9f/src/fields.ts#L820-L826

You would use it like this:

```ts
import * as prismicT from '@prismicio/types'

type ImageSlice = prismicT.SharedSlice<
  "image",
  ImageSliceDefault | ImageSliceWithCaption
>

type ImageSliceDefault = prismicT.SharedSliceVariation<
  "default",
  {
    image: prismicT.ImageField;
  },
  never
>

type ImageSliceWIthCaption = prismicT.SharedSliceVariation<
  "withCaption",
  {
    image: prismicT.ImageField;
    caption: prismicT.RichTextField;
  },
  never
>
```

---

We just released a new tool call `prismic-ts-codegen` that can generate all of these types for you automatically. I would recommend using that tool over writing the types by hand.

```sh
# Install the codegen tool
npm install --save-dev prismic-ts-codegen @prismicio/types

# Create a prismicCodegen.config.ts configuration file
npx prismic-ts-codegen init

# Generate types
npx prismic-ts-codegen
```

You can learn more about the tool here: https://prismic.io/docs/technical-reference/prismic-ts-codegen
